config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'users/new'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get 'home/about'

  root 'home#index'

 get "home/help"
 get "home/about"
 get "home/contact"
 get "/login", to: "sessions#new"
post "/login", to: "sessions#create"
delete "/logout", to: "sessions#destroy"
 resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email = email.downcase }
    validates :name, presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
    format: { with: VALID_EMAIL_REGEX },
    uniqueness: true
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include SessionsHelper
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
    end
   def about
   end
def header
end
    def contact
    end
      def help
      end
      def login
      end
      def signup
        
end

end

app/controllers/home_controller_test.rb
require "test_helper"
class homeControllerTest < ActionDispatch::IntegrationTest
test "should get home" do
    get home_home_url
assert_response :success
assert_select "title", "Ruby on Rails Tutorial Sample App"
end
test "should get help" do
get home_help_url
assert_response :success
assert_select "title", "Help | Ruby on Rails Tutorial Sample
App"
end
test "should get about" do
get home_about_url
assert_response :success
assert_select "title", "About | Ruby on Rails Tutorial Sample
App"
end
test "should get contact" do
get home_contact_url
assert_response :success
assert_select "title", "Contact | Ruby on Rails Tutorial
Sample App"
end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
    user = User.find_by(email: params[:email].downcase)
    if user && user.authenticate(params[:password])
        reset_session
        log_in user
        redirect_to user
        # Log the user in and redirect to the user's show page.
    else
      # Create an error message.
      flash[:danger] = 'Invalid email/password combination' # Not
      quite right!
      render 'new', status: :unprocessable_entity
    end
  end
  def destroy
  end
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find_by(id: params[:id])
  end
  def new
    @user = User.new
    end
    def create
      @user = User.new(user_params)
      if @user.save
        flash[:success] = "Welcome to the Sample App!"
        redirect_to @user
      # Handle a successful save.
      else
      render 'new', status: :unprocessable_entity
      end
      end
      private
      def user_params
      params.require(:user).permit(:name, :email, :password,
      :password_confirmation)
      end
      end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in(user)
        session[:user_id] = user.id
        end
    # Returns the current logged-in user (if any).
def current_user
    if session[:user_id]
    @current_user ||= User.find_by(id: session[:user_id])
    end
    end
    # Returns true if the user is logged in, false otherwise.
def logged_in?
    !current_user.nil?
    end
end

app/helpers/users_helper.rb
module UsersHelper
    # Returns the Gravatar for the given user.
    def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#
    {gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
    end
    end

app/views/home/_header.html.erb
<!-- Navbar Start -->
    <nav class="navbar fixed-top shadow-sm navbar-expand-lg bg-light navbar-light py-3 py-lg-0 px-lg-5">
        <a class="navbar-brand ml-lg-3">
            <h1 class="m-0 display-5"><span class="text-primary">DANG</span>THUC</h1>
        </a>
        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse px-lg-3" id="navbarCollapse">
            <div class="navbar-nav m-auto py-0">
               <a href="home/about" class="nav-item nav-link active">About</a>
                <a href="home/contact" class="nav-item nav-link">Contact</a>
                <a href="#help" class="nav-item nav-link">Help</a>
                <%= link_to "Home",root_path,class:"nav-item nav-link"%>
               
            </div>
            <%= link_to "Sign up",users_new_path,class:"btn btn-outline-primary d-none d-lg-block"%>
            </div>
    </nav>
    <!-- Navbar End -->

app/views/home/about.html.erb
<h1>Contact with Dang Thuc....</h1>

app/views/home/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
Contact the Ruby on Rails Tutorial about the sample app at the
<a href="https://www.railstutorial.org/contact">contact
page</a>.
</p>

app/views/home/index.html.erb
<div class="container">
<script src='https://kit.fontawesome.com/a076d05399.js' crossorigin='anonymous'></script>
        <div class="body d-md-flex align-items-center justify-content-between">
            <div class="box-1 mt-md-0 mt-5">
                <img src="https://images.pexels.com/photos/2399840/pexels-photo-2399840.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500"
                    class="" alt="">
            </div>
            <div class=" box-2 d-flex flex-column h-100">
                <div class="mt-5">
                    <p class="mb-1 h-1">Create Account.</p>
                    <p class="text-muted mb-2">Share your thouhts with the world form today.</p>
                    <div class="d-flex flex-column ">
                        <p class="text-muted mb-2">Continue with...</p>
                        <div class="d-flex align-items-center">
                            <a href="#" class="box me-2 selectio">
                                <span class="fab fa-facebook-f mb-2"></span>
                                <p class="mb-0">Facebook</p>
                            </a>
                            <a href="#" class="box me-2">
                                <span class="fab fa-google mb-2"></span>
                                <p class="mb-0">Google</p>
                            </a>
                            <a href="#" class="box">
                                <span class="far fa-envelope mb-2"></span>
                                <p class="mb-0">Email</p>
                            </a>
                        </div>
                        <div class="mt-3">
                            <p class="mb-0 text-muted">Already have an account?</p>
                            
                            <%= link_to "Log in",sessions_new_path,class:"btn btn-outline-primary d-none d-lg-block"%>
                        </div>
                    </div>
                </div>
                <div class="mt-auto">
                    <p class="footer text-muted mb-0 mt-md-0 mt-4">By register you agree with our
                        <span class="p-color me-1">terms and conditions</span>and
                        <span class="p-color ms-1">privacy policy</span>
                    </p>
                </div>
            </div>
            <span class="fas fa-times"></span>
        </div>
    </div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>Shopping</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
   <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>
  <body>
  
  <%= render 'home/header'%>
   
   <div class="container">
   <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
   <br/>
   
  <%= yield %>
    </div>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
<div id="error_explanation">
<div class="alert alert-danger">
The form contains <%= pluralize(@user.errors.count,
"error") %>.</div>
<ul>
<% @user.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
<% end %>
</ul>
</div>
<% end %>

app/views/users/new.html.erb
<div class="container">
<br>
  <div class="center"><strong>Sign up </strong></div>
  </br>
    <div class="row" style="justify-content: center">
    <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @user) do |f| %>
    <%= render 'shared/error_messages' %>
    <%= f.label :name %><%= f.text_field :name, class: 'form-control' %>
    <%= f.label :email %>
    <%= f.email_field :email, class: 'form-control' %>
    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control' %>
    <%= f.label :password_confirmation, "Confirmation" %>
    <%= f.password_field :password_confirmation, class: 'formcontrol' %>
    <%= f.submit "Create my account", class: "btn btn-primary"
    %>
    <% end %>
    </div>
    </div>
    </div>

app/views/users/show.html.erb
<%= @user.name %>, <%= @user.email %>
<% provide(:title, @user.name) %>
<div class="row">
<aside class="col-md-4">
<section class="user_info">
<h1>
<%= gravatar_for @user %>
<%= @user.name %>
</h1>
</section>
</aside>
</div